version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - mvn -v
      - echo Nothing to do in the install phase...
  post_build:
    commands:
      - echo Build completed on `date`
      - zip -r JavaWeb.zip target/JavaWeb.war appspec.yml scripts/*
artifacts:
  files:
    - target/JavaWeb.war
    - appspec.yml
    - scripts/*
