version: 0.2

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install -DskipTests=true
  post_build:
    commands:
      - echo Build completed on `date`
      - zip -r JavaWeb.zip target/JavaWeb.war appspec.yml scripts/*
artifacts:
  files:
    - target/JavaWeb.war
    - appspec.yml
    - scripts/*
